branches:
  only:
  - master
language: groovy
sudo: required
services:
- docker
env:
  global:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  - PPIPER_INFRA_IT_TEST_PROJECT=https://github.com/SAP/cloud-s4-sdk-book
  - PPIPER_INFRA_IT_CF_USERNAME=P2001099548
  - secure: BfL6+c0LpKRiv6J6xbmCmKmAIVBrqwASxy3ddHCSgz+t3Pi9N5OgNYa/9ZY1Bn3qyIDSDFq8egUDlVc28CrCiG0C1Y8sE530W0dsZWuBukpfEaawIqQNr23oj2PQOZLNLaWhhqP3To6VyLY0Qo5/Y/JhQ2MSdPF2KIN0H/zjdOaLYPyLX+G5XYYVDhbWm6chpijw1gd45Q2uYtIC+pIWYo2HUKNCOCeeyG8l+04CkwYCndTG7DJzq43dFYhY1eXO+/9PxPeczyMkwZy/oWezxi/xvNaf2nQXFuqw7q1CVP7szVhqq3qyKVQ/MDtYZHvq7J2ilIPyVPC1NEujh/AszVCHGSNUOiZlchwFYceHCmiuexJpspHNuTXAEooLWk5G/AjyIs0ytVdW3rGUglUfQgPWM0z1OeRy6FrrIJSX5eQRBsrKpYQMOHGnTjLwPj5+S6cSuRAyA+OSEDGWUTqWtMiYAIB2itU4tGxwk+HALvHSte5JsvNLjFehGpz/pf8in8Wyd42ACbyuCV3Q2JDN9LWDXwAHO5RrzdT/1x4qvL7HOeyuHlhfVIc9mi+TGPGOYsTRoFjFLWD9IdgaQymX8C/pJqEJ962EYxHWUc1Kl8Wi8UkpOg3adpl0yDtxH9fH2sqKA3u4uR31/gu+3sZaG/F+Zts4nAI73hwJOJj/NRs=
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
  - stage: Tests
    name: Unit Tests
    before_script:
    - curl -L --output cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script: mvn package --batch-mode
    after_script:
    - JACOCO_SOURCE_PATH="src vars test" ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml
      --input-type jacoco
    - "./cc-test-reporter upload-coverage"
  - name: Docs Build
    if: type = pull_request
    install: docker pull squidfunk/mkdocs-material:3.0.4
    script:
    - |
      cp -r documentation/docs documentation/docs-tmp
      documentation/bin/createDocu.sh vars documentation/docs-tmp/steps
      docker run --rm -it -v ${TRAVIS_BUILD_DIR}:/docs -w /docs/documentation squidfunk/mkdocs-material:3.0.4 build --clean --verbose --strict
  - name: Consumer Tests
    script: cd consumer-test && chmod +x runTests.sh && ./runTests.sh
  - stage: Docs
    name: Deploy
    if: repo = "SAP/jenkins-library" AND branch = master AND NOT type = pull_request
    install:
    - docker pull squidfunk/mkdocs-material:3.0.4
    - "echo \"Found change on master: Deployment of documentation\"\nPRIVATE_KEY=\"cfg/id_rsa\"\nopenssl
      aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in
      cfg/id_rsa.enc -out \"${PRIVATE_KEY}\" -d\nchmod a+x gh-pages-deploy.sh        \ncp
      -r documentation/docs documentation/docs-tmp\ndocumentation/bin/createDocu.sh
      vars documentation/docs-tmp/steps\n"
    script: docker run --rm -it --entrypoint "./gh-pages-deploy.sh" -e "TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}"
      -v ${TRAVIS_BUILD_DIR}:/docs -w /docs squidfunk/mkdocs-material:3.0.4
